
/**************************************************************
 *	
 *	chickendance4, 8 bit, 11025Hz,
 *	1 channel, 670861 bytes/channel
 *	Total Size: 1 * 670861 + 4 (header) = 670905 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Cathey\Downloads\wav2c\wav2c\chickendance4.wav
 *	Time-stamp: Sun Apr 19 13:36:37 2015
 *	
 **************************************************************/

#ifndef __CHICKENDANCE4H__
#define __CHICKENDANCE4H__

#define CHICKENDANCE4FREQ 11025
#define CHICKENDANCE4LEN 670861

extern const unsigned char chickendance4[670861];

#endif /* __CHICKENDANCE4H__ */
