
/**************************************************************
 *	
 *	cluck, 8 bit, 44100Hz,
 *	1 channel, 31738 bytes/channel
 *	Total Size: 1 * 31738 + 4 (header) = 31782 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Cathey\Downloads\wav2c\wav2c\cluck.wav
 *	Time-stamp: Sun Apr 19 13:32:55 2015
 *	
 **************************************************************/

#ifndef __CLUCKH__
#define __CLUCKH__

#define CLUCKFREQ 44100
#define CLUCKLEN 31738

extern const unsigned char cluck[31738];

#endif /* __CLUCKH__ */
