
/**************************************************************
 *	
 *	loserSound, 8 bit, 11025Hz,
 *	1 channel, 65415 bytes/channel
 *	Total Size: 1 * 65415 + 4 (header) = 65459 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Cathey\Downloads\wav2c\wav2c\loserSound.wav
 *	Time-stamp: Fri Mar 06 10:19:17 2015
 *	
 **************************************************************/

#ifndef __LOSERSOUNDH__
#define __LOSERSOUNDH__

#define LOSERSOUNDFREQ 11025
#define LOSERSOUNDLEN 65415

extern const unsigned char loserSound[65415];

#endif /* __LOSERSOUNDH__ */
