
/**************************************************************
 *	
 *	thunder, 8 bit, 11025Hz,
 *	1 channel, 163143 bytes/channel
 *	Total Size: 1 * 163143 + 4 (header) = 163187 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Cathey\Downloads\wav2c\wav2c\thunder.wav
 *	Time-stamp: Sun Apr 19 13:43:21 2015
 *	
 **************************************************************/

#ifndef __THUNDERH__
#define __THUNDERH__

#define THUNDERFREQ 11025
#define THUNDERLEN 163143

extern const unsigned char thunder[163143];

#endif /* __THUNDERH__ */
