
/**************************************************************
 *	
 *	winnerSound, 8 bit, 11025Hz,
 *	1 channel, 18202 bytes/channel
 *	Total Size: 1 * 18202 + 4 (header) = 18246 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Cathey\Downloads\wav2c\wav2c\winnerSound.wav
 *	Time-stamp: Fri Mar 06 10:18:56 2015
 *	
 **************************************************************/

#ifndef __WINNERSOUNDH__
#define __WINNERSOUNDH__

#define WINNERSOUNDFREQ 11025
#define WINNERSOUNDLEN 18202

extern const unsigned char winnerSound[18202];

#endif /* __WINNERSOUNDH__ */
